### ISSUE TITLE
question about adversarial training code in train_UDA.py

### ISSUE THREAD

**Issue by yuzhang03** [valeoai/MTAF#6]
Thank you for sharing the code for your excellent work. I have some basic questions about your implementation.
`            pred_trg_main = interp_target(all_pred_trg_main[i+1]) ## what does [i+1] mean?
            pred_trg_main_list.append(pred_trg_main) 
            pred_trg_target = interp_target(all_pred_trg_main[0]) ## what does [0] mean?
            pred_trg_target_list.append(pred_trg_target)`

In train_UDA.py, line 829-836, why should we use index[i+1] and [0]? What's the meaning of that? Also, where is the definition of the target-agnostic classifier in your code?

Thanks again and look forward to hearing back from you!

**Comment by SportaXD** [comment]
Thank you for your interest in our work.

When created in `train.py`, the MTKT model has `num_classifiers=1+len(cfg.TARGETS)` as parameter (line 93). This MTKT model returns the outputs of all those classifiers. Since all the classifiers have the same architecture, we choose to have the classifier at index `[0]` to be the target-agnostic one and, for each target i, the classifier at index `[i+1]` to be its target-specific one.

In `eval_UDA.py`, you'll notice that we only evaluate the output at the index `[0]`:
`pred_main = pred_main_list[0]` (line 53)

I hope this helps.

**Comment by yuzhang03** [comment]
That solves my confusion. Thanks!
